# Generated by Django 2.2.9 on 2021-11-28 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20211128_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(help_text='Ограничение в 200 символов', max_length=200, verbose_name='Название сообщества'),
        ),
    ]
